### ISSUE TITLE
Deny access if neither namespaces nor labels is provided?

### ISSUE THREAD

**Issue by derlin** [k8spin/prometheus-multi-tenant-proxy#66]
Label support was added in #58 with a warning in the README: 

> *(It could lead to a security issue if the proxy is not configured to use namespaces or labels)*

I am wondering if it wouldn't be better to actually check either labels or namespaces exist during the authentication ? Except if having users without proxying is a feature we want to support?

If we go with that, I hesitate on where this check should arise. My two propositions:

1. add it to the `auth.go::AuthHandler` function:  `if !authorized || (len(namespaces) == 0 && len(labels) == 0`
2. add it to each auth type. Using basic auth, we should check during loading that all users have at least a namespace or a label. For JWT, ensure the claim contains one of both.

**Comment by angelbarrera92** [comment]
That's a good suggestion, i didn't like the implementation i did a few weeks back.

I'll go with the 1st approach. Looks cleaner and easier to understand for the end user and future contributors. We just need to set the right error message in the response instead of letting the query fail.

Niiiice :)

**Comment by derlin** [comment]
Good! I already have the tests and impl for the first option, let me just do a PR.

**Comment by angelbarrera92** [comment]
You solved it by #70 :) Thanks once again @derlin
